# header - menu
menu:
  Home      : /                # 主页
  # Document: /document/       # 文档
  About     : /about          # 关于
  Friends   : /links           # 友链


post_menu_side: right  # 默认 right


favicon:
  small: null
  medium: null
  apple_touch_icon: null
  safari_pinned_tab: null
